### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by GiggleLiu** [CodingThrust/CenterOfQSTWebsite#2]
* [x] vector graph for logo, `svg` and `ico` formats, and make them darker. (Jinguo Liu, Peng Chen)
* Complete the About page: https://codingthrust.github.io/CenterOfQSTWebsite/about/
    * [x] Recruitment information
    * [ ] Add social medias, Twitter, wechat et al. (?)
* [x] Check the profiles in the [team page](https://codingthrust.github.io/CenterOfQSTWebsite/team/). (ALL, especially Haoxiang Li, please click the link to see your own profile)
* [x] modify the 4 directions in the [home page](https://codingthrust.github.io/CenterOfQSTWebsite/), change their images, otherwise they are too similar to the one on IAS website: https://www.notion.so/Research-directions-needs-everyone-s-input-8620a87f273d44dbade3debec4d8a767 . Also, please make sure they have the same height in the webpage! (Peng Chen, Xiaoxiao Wu, Haoxiang Li and Qiming Shao)
* [x] Add more items in the [research](https://codingthrust.github.io/CenterOfQSTWebsite/research/) page. (ALL)
* [x] Sort events and researches by their time (Jinguo Liu).
* [x] The layout in the profile page, and the research page. Do not use tables! (Jinguo Liu)
* [ ] ~~Do not use the default home page image (it looks pretty good, so left it unchanged)~~
* [x] Rescale all images

## How to update information?
If you want to update information, please edit the corresponding notion database directly
* [Team](https://www.notion.so/eb1998c2a7c54c649aa88ca82acc101d?v=426ce48fef5d49f3af39a6dfd83c065a)
* [Research](https://www.notion.so/003d7922fb114b159c1a8323e9324ee2?v=9c2e6aa609e541fb92c3ce933f0f9907)

If you do not have the notion access, please send me the required information through wechat.
### Research
![image](https://user-images.githubusercontent.com/6257240/190995907-5012c94e-09a4-481e-a968-c3441322e2f3.png)
### Faculty
![image](https://user-images.githubusercontent.com/6257240/190996218-327dc43b-ee63-436e-9ba3-7221129c06ea.png)

**Comment by GiggleLiu** [comment]
Bei: The about page: https://academicjobsonline.org/ajo/jobs/19998
参考这个吧，改改放我们自己网页上。
